### ISSUE TITLE
HYP_REST_ENDPOINT=http://192.168.6.111:7050 node exp-server.js ? error:

### ISSUE THREAD

**Issue by yonchin** [yeasy/docker-blockchain-explorer#4]
Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

**Comment by fstepho** [comment]
Same here with docker image and Hyperledger fabric 1.0

$ docker ps
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
1628685e5ebc        hyperledger/fabric-peer:x86_64-1.0.0                                   "peer node start -..."   23 hours ago        Up 23 hours         0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
78f26a8cde16        hyperledger/fabric-orderer:x86_64-1.0.0                                "orderer"                23 hours ago        Up 23 hours         0.0.0.0:7050->7050/tcp                           orderer.example.com
7c292207ae71        hyperledger/fabric-ca:x86_64-1.0.0                                     "sh -c 'fabric-ca-..."   23 hours ago        Up 23 hours         0.0.0.0:7054->7054/tcp                           ca.org1.example.com
92b72096c630        hyperledger/fabric-couchdb:x86_64-1.0.0                                "tini -- /docker-e..."   23 hours ago        Up 23 hours         4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb

$ docker run -e HYP_REST_ENDPOINT=http://192.168.1.19:7050 hyperledger/blockchain-explorer

Compiling all doT templates...
Compiling HyperlegerExplorer.jst to file
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }

**Comment by yeasy** [comment]
There's no support to fabric 1.0 now.
